export type IconKey = "keys" | "mic" | "drum" | "headphones" | "note";
export type Region = "tamoul";

export type Artist = {
  slug: string;
  image: string;
  icon: IconKey;
  color: string;
  name: string;
  tag: string;
  region: Region;
  featured: boolean;
  short: string;
  bio: string[];
  keyDates: string[];
  latest: string;
};

export const ARTISTS: Artist[] = [
  {
    slug: "ar-rahman",
    image: "/artists/ar-rahman.jpg",
    icon: "headphones",
    color: "from-blue-600 to-blue-400",
    name: "A.R. Rahman",
    tag: "Musique de film",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur oscarisé (Slumdog Millionaire), surnommé le « Mozart de Madras ». Ses concerts mêlent orchestre symphonique, musique électronique et sonorités traditionnelles indiennes.",
    bio: [
      "Né à Madras (aujourd'hui Chennai), A.R. Rahman s'impose dès les années 1990 comme l'un des compositeurs les plus innovants du cinéma indien, en mêlant instruments classiques indiens, chœurs, et production électronique moderne.",
      "Sa notoriété devient mondiale avec la bande originale de Slumdog Millionaire, récompensée de deux Oscars et de deux Grammy Awards. Il continue de composer pour le cinéma indien et international et donne régulièrement de grands concerts symphoniques à travers le monde.",
    ],
    keyDates: [
      "1992 — Débute au cinéma avec la bande originale du film Roja.",
      "1995 — Compose la musique du film Bombay, saluée internationalement.",
      "2008 — Remporte deux Oscars et deux Grammy Awards pour Slumdog Millionaire.",
    ],
    latest:
      "En tournée symphonique aux États-Unis en juillet 2026 (San Francisco Symphony le 2 juillet, Wolf Trap le 10 juillet, Houston Symphony les 24 et 25 juillet), avec d'autres dates prévues jusqu'en août.",
  },
  {
    slug: "anirudh-ravichander",
    image: "/artists/anirudh-ravichander.jpg",
    icon: "headphones",
    color: "from-teal-600 to-teal-400",
    name: "Anirudh Ravichander",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Figure incontournable du cinéma tamoul (Kollywood), connu pour ses bandes originales énergiques et ses concerts électrisants qui remplissent les stades en Inde du Sud.",
    bio: [
      "Repéré très jeune par le réalisateur Mani Ratnam, Anirudh Ravichander s'impose rapidement comme l'un des compositeurs les plus populaires du cinéma tamoul, avec un style qui mélange pop, hip-hop et sonorités électroniques.",
      "Ses tournées et concerts live, portés par une forte présence scénique, attirent un public massif en Inde du Sud comme au sein de la diaspora tamoule à l'international.",
    ],
    keyDates: [
      "2011 — Perce avec le titre viral « Why This Kolaveri Di » (film 3), succès national puis international.",
      "2010s-2020s — Devient l'un des compositeurs et interprètes tamouls les plus streamés.",
    ],
    latest:
      "En tournée « Anirudh XV Tour 2026 » : Dubaï le 11 janvier, Paris (Adidas Arena) le 18 avril, Trenton (New Jersey) le 30 août et Toronto le 5 septembre 2026.",
  },
  {
    slug: "harris-jayaraj",
    image: "/artists/harris-jayaraj.jpg",
    icon: "note",
    color: "from-violet-600 to-violet-400",
    name: "Harris Jayaraj",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur emblématique du cinéma tamoul depuis les années 2000, réputé pour ses mélodies romantiques et ses orchestrations soignées.",
    bio: [
      "Harris Jayaraj s'est fait connaître à la fin des années 1990 pour ses orchestrations riches et ses mélodies romantiques, devenant l'un des compositeurs de référence du cinéma tamoul.",
      "Son style, marqué par des arrangements soignés mêlant cordes, chœurs et sonorités contemporaines, a profondément influencé toute une génération de musique de film en Inde du Sud.",
    ],
    keyDates: [
      "1999 — Débute avec la bande originale du film Minnale, immédiatement remarquée.",
      "Années 2000 — Enchaîne les succès qui font de lui une référence du cinéma tamoul romantique.",
    ],
    latest:
      "A composé la musique de Kadhal Reset Repeat, comédie musicale romantique tamoule sortie en salles le 6 mars 2026.",
  },
  {
    slug: "yuvan-shankar-raja",
    image: "/artists/yuvan-shankar-raja.jpg",
    icon: "keys",
    color: "from-rose-600 to-rose-400",
    name: "Yuvan Shankar Raja",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur prolifique et polyvalent du cinéma tamoul, entre bandes originales pop, folk et musique de film, avec une large base de fans.",
    bio: [
      "Fils du compositeur Ilaiyaraaja, Yuvan Shankar Raja se forge sa propre identité musicale dès les années 1990 en explorant un large éventail de styles, du folk tamoul à la pop électronique.",
      "Réputé pour sa productivité et sa capacité à se réinventer, il reste l'un des compositeurs les plus sollicités du cinéma tamoul, avec une fanbase fidèle qui suit ses concerts avec ferveur.",
    ],
    keyDates: [
      "1997 — Débute comme compositeur à seulement 17 ans avec le film Aravindhan.",
      "2020s — Signe la bande originale du film à succès The Greatest of All Time.",
    ],
    latest:
      "Concert prévu le 4 juillet 2026 à l'Expo Ground de Pondichéry, après une tournée en Australie en 2025 (Sydney, Melbourne) et la sortie de l'album Jayam Ravi Hits le 8 septembre 2025.",
  },
  {
    slug: "ilaiyaraaja",
    image: "/artists/ilaiyaraaja.jpg",
    icon: "keys",
    color: "from-emerald-600 to-emerald-400",
    name: "Ilaiyaraaja",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Surnommé « l'Isai Gnani » (le sage de la musique), il a composé plus de 4 500 chansons et la musique de plus de 1 000 films en cinq décennies de carrière.",
    bio: [
      "Figure fondatrice de la musique de film tamoule moderne, Ilaiyaraaja a introduit dès la fin des années 1970 l'usage de l'orchestration occidentale mêlée aux ragas classiques indiens et aux mélodies folkloriques du Tamil Nadu.",
      "Père du compositeur Yuvan Shankar Raja, il reste actif sur scène avec de grandes tournées symphoniques rendant hommage à son répertoire, y compris à l'international.",
    ],
    keyDates: [
      "1976 — Débute comme compositeur avec le film Annakkili.",
      "Record du monde — Seul compositeur de l'histoire du cinéma à avoir signé la musique de plus de 1 000 films.",
    ],
    latest:
      "Tournée « Ilaiyaraaja Live 2026 » : concert à Chennai après une étape à Londres, puis dates au Royaume-Uni (OVO Arena Wembley le 10 juillet) et aux États-Unis (EagleBank Arena) dans le cadre du « Raja 50 USA Tour ».",
  },
  {
    slug: "gv-prakash-kumar",
    image: "/artists/gv-prakash-kumar.jpg",
    icon: "note",
    color: "from-cyan-600 to-cyan-400",
    name: "G.V. Prakash Kumar",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Neveu d'A.R. Rahman, il s'est imposé comme l'un des compositeurs les plus prolifiques du cinéma tamoul, avant de devenir aussi acteur.",
    bio: [
      "G.V. Prakash Kumar débute très jeune dans l'industrie du cinéma tamoul et se forge rapidement une identité musicale mêlant mélodies populaires et sonorités contemporaines.",
      "En parallèle de sa carrière de compositeur, il s'est également imposé comme acteur dans plusieurs films tamouls à succès.",
    ],
    keyDates: [
      "2006 — Débute comme compositeur avec le film Veyyil.",
      "Janvier 2026 — Compose la musique de Parasakthi, son 100e film en tant que compositeur.",
    ],
    latest:
      "A composé la musique de Parasakthi (sorti le 10 janvier 2026) et apparaît en tant qu'acteur dans Happy Raj, sorti le 27 mars 2026.",
  },
  {
    slug: "santhosh-narayanan",
    image: "/artists/santhosh-narayanan.jpg",
    icon: "headphones",
    color: "from-orange-600 to-orange-400",
    name: "Santhosh Narayanan",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Compositeur tamoul à l'univers sonore singulier, mêlant folk du Tamil Nadu, hip-hop et musique électronique indépendante.",
    bio: [
      "Repéré grâce à sa collaboration avec le réalisateur Pa. Ranjith, Santhosh Narayanan s'est distingué par des bandes originales ancrées dans les musiques populaires et folkloriques tamoules, avec une touche résolument moderne.",
      "Il collabore aussi régulièrement avec des artistes internationaux, contribuant à faire connaître la scène musicale tamoule indépendante hors d'Inde.",
    ],
    keyDates: [
      "2012 — Révélé par la bande originale du film Attakathi.",
      "Octobre 2025 — Collabore avec Ed Sheeran sur l'EP Play (The Remixes).",
    ],
    latest:
      "A composé la musique du film Vaa Vaathiyaar, sorti le 14 janvier 2026, et a produit le single « Vari Vari » de la chanteuse Dhee en 2026.",
  },
  {
    slug: "sid-sriram",
    image: "/artists/sid-sriram.jpg",
    icon: "mic",
    color: "from-fuchsia-600 to-fuchsia-400",
    name: "Sid Sriram",
    tag: "Chanteur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Chanteur né en Inde et formé aux États-Unis, il marie musique carnatique traditionnelle et pop/R&B contemporains, aussi bien dans le cinéma tamoul qu'en tant qu'artiste solo.",
    bio: [
      "Formé dès l'enfance à la musique carnatique puis élevé en Californie, Sid Sriram développe un style unique mêlant tradition indienne et influences R&B et hip-hop américaines.",
      "Très demandé comme chanteur playback dans le cinéma tamoul, il mène en parallèle une carrière solo internationale, avec des collaborations remarquées dans l'industrie musicale américaine.",
    ],
    keyDates: [
      "2012 — Débute comme chanteur playback dans le cinéma tamoul.",
      "2023 — Sort Sidharth, son premier album entièrement en anglais, chez Def Jam.",
    ],
    latest:
      "Tournée nord-américaine à l'automne 2026, avec des dates en septembre (Illinois, New Jersey, Virginie, Washington, Californie) et des concerts au Blue Note de New York et Los Angeles en novembre 2026.",
  },
  {
    slug: "d-imman",
    image: "/artists/d-imman.jpg",
    icon: "note",
    color: "from-lime-600 to-lime-400",
    name: "D. Imman",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Compositeur tamoul réputé pour ses mélodies mélodieuses et ses bandes originales rurales, récompensé à plusieurs reprises pour son travail dans le cinéma tamoul.",
    bio: [
      "D. Imman se distingue par des compositions mélodiques marquées par des sonorités folkloriques et rurales, très appréciées dans le cinéma tamoul populaire.",
      "Il a composé la musique de nombreux films à succès et reste l'un des compositeurs les plus actifs de l'industrie, avec plusieurs sorties chaque année.",
    ],
    keyDates: [
      "2008 — Débute avec la bande originale du film Vil Ambu.",
      "2010s — Multiplie les récompenses pour ses bandes originales dans le cinéma tamoul.",
    ],
    latest:
      "A composé la musique du film Vadam, sorti le 6 mars 2026, ainsi que celle de plusieurs autres sorties tamoules de l'année.",
  },
  {
    slug: "hiphop-tamizha",
    image: "/artists/hiphop-tamizha.jpg",
    icon: "headphones",
    color: "from-red-600 to-red-400",
    name: "Hiphop Tamizha (Adhi)",
    tag: "Duo hip-hop tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Duo formé d'Adhi et Jeeva, pionnier du hip-hop en langue tamoule, connu pour ses titres énergiques et ses concerts très suivis en Inde du Sud.",
    bio: [
      "Basé à Chennai, le duo Hiphop Tamizha est considéré comme le pionnier du hip-hop en tamoul, mêlant rap, pop et sonorités traditionnelles dans des morceaux devenus des hymnes populaires.",
      "Adhi, la voix et le compositeur principal du duo, s'est aussi imposé comme acteur et réalisateur dans le cinéma tamoul.",
    ],
    keyDates: [
      "2014 — Premier album qui installe le duo comme pionnier du hip-hop tamoul.",
      "Plusieurs titres devenus viraux, dont « Ethir Neechal » et « Sakkarakatti ».",
    ],
    latest:
      "Concert prévu le 7 mars 2026 au YMCA Ground de Chennai ; pas de tournée internationale annoncée pour le moment.",
  },
  {
    slug: "dhee",
    image: "/artists/dhee.jpg",
    icon: "mic",
    color: "from-pink-600 to-pink-400",
    name: "Dhee",
    tag: "Chanteuse tamoule",
    region: "tamoul",
    featured: false,
    short:
      "Révélée par le titre viral « Rowdy Baby », elle s'impose depuis comme l'une des voix montantes de la pop tamoule contemporaine.",
    bio: [
      "Dhee se fait connaître en 2018 avec « Rowdy Baby » (film Maari 2, avec Yuvan Shankar Raja), devenu l'une des vidéos musicales indiennes les plus vues au monde.",
      "Depuis, elle poursuit une carrière solo entre pop tamoule et collaborations internationales, en explorant des sonorités plus électroniques et personnelles.",
    ],
    keyDates: [
      "2018 — Explose avec « Rowdy Baby », plus d'1,5 milliard de vues sur YouTube.",
      "Octobre 2025 — Apparaît sur l'EP Play (The Remixes) d'Ed Sheeran.",
    ],
    latest:
      "A sorti plusieurs nouveaux titres en 2026, dont « Like I Want You » (13 mars 2026) et le single « Vari Vari », produit par Santhosh Narayanan.",
  },
  {
    slug: "chinmayi-sripada",
    image: "/artists/chinmayi-sripada.jpg",
    icon: "mic",
    color: "from-purple-600 to-purple-400",
    name: "Chinmayi Sripada",
    tag: "Chanteuse tamoule",
    region: "tamoul",
    featured: false,
    short:
      "Chanteuse et actrice de doublage prolifique, active dans le cinéma tamoul, télougou, kannada, malayalam et hindi depuis plus de 20 ans.",
    bio: [
      "Chinmayi Sripada s'est imposée dès les années 2000 comme l'une des chanteuses de playback les plus polyvalentes du sud de l'Inde, avant de développer également une importante carrière de doublage.",
      "Elle poursuit aujourd'hui ses activités de chanteuse et de doubleuse dans plusieurs langues, tout en étant également entrepreneuse.",
    ],
    keyDates: [
      "2001 — Débute comme chanteuse playback dans le cinéma tamoul.",
      "2023 — Fait son retour au doublage dans le cinéma tamoul après plusieurs années d'absence.",
    ],
    latest:
      "A prêté sa voix dans le film Karuppu (2026) et a doublé pour le film télougou Dacoit: A Love Story en 2026.",
  },
  {
    slug: "sp-balasubrahmanyam",
    image: "/artists/sp-balasubrahmanyam.jpg",
    icon: "mic",
    color: "from-teal-700 to-teal-500",
    name: "S.P. Balasubrahmanyam",
    tag: "Légende du playback sud-indien",
    region: "tamoul",
    featured: false,
    short:
      "Détenteur d'un record du monde pour le nombre de chansons enregistrées, figure la plus emblématique du playback sud-indien.",
    bio: [
      "S.P. Balasubrahmanyam a marqué le cinéma tamoul, télougou, kannada et hindi par une carrière de plus de quatre décennies, enregistrant des dizaines de milliers de chansons dans une quinzaine de langues. Il est décédé le 25 septembre 2020 des suites de la COVID-19.",
    ],
    keyDates: ["1966 — Débute sa carrière de playback.", "25 septembre 2020 — Décès."],
    latest: "Son héritage est célébré chaque année lors de nombreux concerts hommage à travers l'Inde du Sud.",
  },
  {
    slug: "ks-chithra",
    image: "/artists/ks-chithra.jpg",
    icon: "mic",
    color: "from-purple-700 to-purple-500",
    name: "K.S. Chithra",
    tag: "Chanteuse playback sud-indienne",
    region: "tamoul",
    featured: false,
    short: "L'une des chanteuses de playback les plus récompensées du Sud de l'Inde, active depuis les années 1980.",
    bio: [
      "K.S. Chithra a marqué le cinéma tamoul, malayalam et télougou par une voix versatile, remportant de nombreux National Film Awards au cours de sa carrière.",
    ],
    keyDates: ["1979 — Débute sa carrière.", "1980s-2000s — Multiplie les National Film Awards de la meilleure chanteuse playback."],
    latest: "Reste active en concert dans le Sud de l'Inde et au sein de la diaspora.",
  },
  {
    slug: "karthik",
    image: "/artists/karthik.jpg",
    icon: "mic",
    color: "from-cyan-700 to-cyan-500",
    name: "Karthik",
    tag: "Chanteur playback tamoul",
    region: "tamoul",
    featured: false,
    short: "Chanteur de playback tamoul très populaire dans les années 2000-2010, connu pour ses ballades romantiques.",
    bio: [
      "Karthik s'est imposé dans le cinéma tamoul par des interprétations intenses de chansons d'amour, devenant l'une des voix masculines les plus demandées de sa génération.",
    ],
    keyDates: ["2003 — Perce dans le cinéma tamoul.", "2010s — Multiplie les tubes romantiques au cinéma."],
    latest: "Se produit régulièrement en concert en Inde du Sud et à l'international.",
  },
  {
    slug: "vijay-yesudas",
    image: "/artists/vijay-yesudas.jpg",
    icon: "mic",
    color: "from-green-700 to-green-500",
    name: "Vijay Yesudas",
    tag: "Chanteur playback sud-indien",
    region: "tamoul",
    featured: false,
    short: "Fils de la légende K.J. Yesudas, il s'est forgé sa propre carrière de chanteur playback dans le Sud de l'Inde.",
    bio: [
      "Vijay Yesudas a construit une carrière remarquée dans le cinéma tamoul et malayalam, saluée par plusieurs récompenses nationales et régionales.",
    ],
    keyDates: ["2004 — Débute sa carrière de playback.", "2010s — Multiplie les récompenses régionales."],
    latest: "Se produit régulièrement en concert dans le Sud de l'Inde.",
  },
  {
    slug: "shweta-mohan",
    image: "/artists/shweta-mohan.jpg",
    icon: "mic",
    color: "from-rose-700 to-rose-500",
    name: "Shweta Mohan",
    tag: "Chanteuse playback sud-indienne",
    region: "tamoul",
    featured: false,
    short: "Chanteuse de playback active dans le cinéma tamoul et malayalam depuis le début des années 2000.",
    bio: [
      "Shweta Mohan s'est imposée comme l'une des voix féminines régulières du cinéma sud-indien, appréciée pour sa polyvalence entre mélodies douces et morceaux dansants.",
    ],
    keyDates: ["2003 — Débute sa carrière de playback.", "2010s-2020s — Multiplie les collaborations avec les grands compositeurs du Sud."],
    latest: "Se produit régulièrement en concert en Inde du Sud et au sein de la diaspora.",
  },
  {
    slug: "deva",
    image: "/artists/deva.jpg",
    icon: "keys",
    color: "from-amber-700 to-amber-500",
    name: "Deva",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur vétéran du cinéma tamoul, très populaire dans les années 1990-2000 pour ses mélodies folk et festives.",
    bio: [
      "Deva s'est imposé dans les années 1990 comme l'un des compositeurs les plus prolifiques du cinéma tamoul, avec un style mêlant folk du Tamil Nadu et orchestrations populaires.",
    ],
    keyDates: ["1988 — Débute sa carrière de compositeur.", "1990s-2000s — Devient l'un des compositeurs les plus demandés du cinéma tamoul populaire."],
    latest: "Reste une référence des bandes originales tamoules des années 1990-2000, régulièrement reprises en concert.",
  },
  {
    slug: "vidyasagar",
    image: "/artists/vidyasagar.jpg",
    icon: "keys",
    color: "from-sky-700 to-sky-500",
    name: "Vidyasagar",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul et télougou réputé pour ses mélodies romantiques soignées, actif depuis les années 1990.",
    bio: [
      "Vidyasagar s'est fait connaître par des bandes originales mélodieuses marquées par des arrangements orchestraux riches, dans le cinéma tamoul comme télougou.",
    ],
    keyDates: ["1990 — Débute sa carrière de compositeur.", "1990s-2000s — Multiplie les succès dans le cinéma tamoul romantique."],
    latest: "Continue de composer ponctuellement pour le cinéma sud-indien.",
  },
  {
    slug: "bharadwaj",
    image: "/artists/bharadwaj.jpg",
    icon: "note",
    color: "from-emerald-700 to-emerald-500",
    name: "Bharadwaj",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul connu pour ses mélodies douces et ses musiques de film à forte teneur émotionnelle.",
    bio: [
      "Bharadwaj s'est distingué dans le cinéma tamoul par des compositions mélodiques sensibles, souvent associées à des films dramatiques ou romantiques.",
    ],
    keyDates: ["1999 — Débute sa carrière de compositeur.", "2000s — Multiplie les bandes originales remarquées du cinéma tamoul."],
    latest: "Continue de composer pour le cinéma tamoul.",
  },
  {
    slug: "srikanth-deva",
    image: "/artists/srikanth-deva.jpg",
    icon: "headphones",
    color: "from-orange-700 to-orange-500",
    name: "Srikanth Deva",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul très prolifique des années 2000, connu pour ses morceaux festifs et dansants.",
    bio: [
      "Srikanth Deva s'est imposé dans les années 2000 par un rythme de production très soutenu, avec des bandes originales populaires et festives pour le cinéma tamoul commercial.",
    ],
    keyDates: ["2003 — Débute sa carrière de compositeur.", "2000s — Devient l'un des compositeurs les plus prolifiques du cinéma tamoul."],
    latest: "Continue de composer pour le cinéma tamoul.",
  },
  {
    slug: "ghibran",
    image: "/artists/ghibran.jpg",
    icon: "keys",
    color: "from-indigo-600 to-indigo-400",
    name: "Ghibran",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul contemporain réputé pour ses bandes originales atmosphériques et son travail sur la musique de film indépendante.",
    bio: [
      "Ghibran s'est fait remarquer par des compositions subtiles et une utilisation raffinée de l'orchestration, s'imposant comme une voix singulière du cinéma tamoul contemporain.",
    ],
    keyDates: ["2011 — Révélé par la bande originale du film Vaayai Moodi Pesavum.", "2010s-2020s — Multiplie les collaborations avec le cinéma tamoul et télougou."],
    latest: "Continue de composer pour le cinéma tamoul et télougou.",
  },
  {
    slug: "sam-cs",
    image: "/artists/sam-cs.jpg",
    icon: "drum",
    color: "from-red-700 to-red-500",
    name: "Sam C.S.",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul contemporain réputé pour ses musiques de film intenses, notamment sur des films d'action à succès.",
    bio: [
      "Sam C.S. s'est imposé dans les années 2010-2020 par des musiques de film puissantes, en particulier sur des films d'action et de gangster devenus de grands succès populaires.",
    ],
    keyDates: ["2016 — Débute sa carrière de compositeur.", "2020s — Compose la musique de plusieurs films d'action tamouls à très grand succès."],
    latest: "Continue de composer pour de grandes productions tamoules.",
  },
  {
    slug: "sean-roldan",
    image: "/artists/sean-roldan.jpg",
    icon: "mic",
    color: "from-teal-700 to-teal-500",
    name: "Sean Roldan",
    tag: "Chanteur/compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Auteur-compositeur-interprète tamoul à l'univers folk et indépendant, apprécié pour son authenticité.",
    bio: [
      "Sean Roldan s'est fait connaître par des compositions mêlant folk tamoul et sonorités indépendantes modernes, apportant une touche singulière au cinéma tamoul.",
    ],
    keyDates: ["2010s — Débute sa carrière de compositeur et interprète.", "2010s-2020s — Multiplie les collaborations avec le cinéma tamoul indépendant."],
    latest: "Continue de composer et de se produire en concert acoustique en Inde du Sud.",
  },
  {
    slug: "justin-prabhakaran",
    image: "/artists/justin-prabhakaran.jpg",
    icon: "keys",
    color: "from-violet-700 to-violet-500",
    name: "Justin Prabhakaran",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul révélé par le film à succès 96, connu pour ses mélodies nostalgiques.",
    bio: [
      "Justin Prabhakaran s'est fait connaître par des compositions empreintes de nostalgie et d'émotion, en particulier grâce au film 96, dont la bande originale a marqué le public tamoul.",
    ],
    keyDates: ["2018 — Révélé par la bande originale du film 96.", "2010s-2020s — Multiplie les collaborations avec le cinéma tamoul."],
    latest: "Continue de composer pour le cinéma tamoul.",
  },
  {
    slug: "leon-james",
    image: "/artists/leon-james.jpg",
    icon: "drum",
    color: "from-gray-700 to-gray-500",
    name: "Leon James",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur tamoul contemporain connu pour ses musiques de film percutantes, notamment sur des films engagés.",
    bio: [
      "Leon James s'est imposé par des bandes originales puissantes accompagnant des films tamouls à forte portée sociale, ainsi que des productions d'action à grand succès.",
    ],
    keyDates: ["2010s — Débute sa carrière de compositeur.", "2020s — Compose la musique de plusieurs films tamouls remarqués."],
    latest: "Continue de composer pour de grandes productions tamoules.",
  },
  {
    slug: "karthik-raja",
    image: "/artists/karthik-raja.jpg",
    icon: "keys",
    color: "from-lime-700 to-lime-500",
    name: "Karthik Raja",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short: "Fils du compositeur Ilaiyaraaja et frère de Yuvan Shankar Raja, il mène sa propre carrière de compositeur dans le cinéma tamoul.",
    bio: [
      "Karthik Raja compose pour le cinéma tamoul depuis le début des années 1990, avec un style influencé par l'héritage musical familial tout en développant sa propre identité.",
    ],
    keyDates: ["1992 — Débute sa carrière de compositeur.", "1990s-2020s — Poursuit une carrière régulière dans le cinéma tamoul."],
    latest: "Continue de composer pour le cinéma tamoul.",
  },
  {
    slug: "premgi-amaren",
    image: "/artists/premgi-amaren.jpg",
    icon: "headphones",
    color: "from-cyan-700 to-cyan-500",
    name: "Premgi Amaren",
    tag: "Compositeur/acteur tamoul",
    region: "tamoul",
    featured: false,
    short: "Compositeur et acteur tamoul, connu pour ses bandes originales populaires et ses rôles comiques au cinéma.",
    bio: [
      "Premgi Amaren mène une double carrière de compositeur et d'acteur dans le cinéma tamoul, appréciée pour des morceaux festifs et des rôles souvent comiques.",
    ],
    keyDates: ["2000s — Débute sa carrière de compositeur.", "2010s-2020s — Poursuit en parallèle une carrière d'acteur remarquée."],
    latest: "Continue de composer et d'apparaître au cinéma tamoul.",
  },
  {
    slug: "haricharan",
    image: "/artists/haricharan.jpg",
    icon: "mic",
    color: "from-blue-700 to-blue-500",
    name: "Haricharan",
    tag: "Chanteur playback tamoul",
    region: "tamoul",
    featured: false,
    short: "Chanteur de playback tamoul apprécié pour ses ballades romantiques, actif depuis la fin des années 2000.",
    bio: [
      "Haricharan s'est imposé dans le cinéma tamoul par des interprétations sensibles de chansons d'amour, devenant l'une des voix masculines régulières de l'industrie.",
    ],
    keyDates: ["2008 — Perce dans le cinéma tamoul.", "2010s-2020s — Multiplie les collaborations avec les grands compositeurs tamouls."],
    latest: "Se produit régulièrement en concert en Inde du Sud et au sein de la diaspora.",
  },
  {
    slug: "nakash-aziz",
    image: "/artists/nakash-aziz.jpg",
    icon: "mic",
    color: "from-fuchsia-700 to-fuchsia-500",
    name: "Nakash Aziz",
    tag: "Chanteur playback tamoul",
    region: "tamoul",
    featured: false,
    short: "Chanteur de playback très polyvalent, actif dans le cinéma tamoul, télougou, kannada et hindi.",
    bio: [
      "Nakash Aziz s'est imposé grâce à sa polyvalence linguistique et à son énergie vocale, devenant l'une des voix masculines les plus demandées du cinéma sud-indien pour les morceaux festifs.",
    ],
    keyDates: ["2000s — Débute sa carrière de chanteur playback.", "2010s-2020s — Multiplie les tubes dansants dans plusieurs langues."],
    latest: "Se produit régulièrement en concert en Inde du Sud et à l'international.",
  },
  {
    slug: "andrea-jeremiah",
    image: "/artists/andrea-jeremiah.jpg",
    icon: "mic",
    color: "from-rose-700 to-rose-500",
    name: "Andrea Jeremiah",
    tag: "Chanteuse/actrice tamoule",
    region: "tamoul",
    featured: false,
    short: "Chanteuse et actrice tamoule à la voix distinctive, appréciée aussi bien au cinéma qu'en tant qu'interprète.",
    bio: [
      "Andrea Jeremiah mène une double carrière de chanteuse et d'actrice dans le cinéma tamoul, avec une voix reconnaissable utilisée sur des morceaux marquants de plusieurs bandes originales.",
    ],
    keyDates: ["2000s — Débute sa carrière de chanteuse et actrice.", "2010s-2020s — Multiplie les collaborations avec de grands compositeurs tamouls."],
    latest: "Se produit occasionnellement en concert en Inde du Sud.",
  },
  {
    slug: "arivu",
    image: "/artists/arivu.jpg",
    icon: "headphones",
    color: "from-green-700 to-green-500",
    name: "Arivu",
    tag: "Rappeur/parolier tamoul",
    region: "tamoul",
    featured: false,
    short: "Rappeur et parolier tamoul révélé par le titre viral « Enjoy Enjaami », figure majeure du hip-hop engagé tamoul.",
    bio: [
      "Arivu s'est fait connaître par « Enjoy Enjaami » (avec Dhee), un titre devenu viral mondialement et mêlant folk tamoul et sonorités hip-hop, porteur d'un message social fort.",
    ],
    keyDates: ["2021 — Explose avec « Enjoy Enjaami », des centaines de millions de vues sur YouTube.", "2020s — Multiplie les collaborations engagées dans la musique tamoule."],
    latest: "Continue de sortir de la musique et de se produire en concert en Inde du Sud et à l'international.",
  },
  {
    slug: "velmurugan",
    image: "/artists/velmurugan.jpg",
    icon: "drum",
    color: "from-yellow-700 to-yellow-500",
    name: "Velmurugan",
    tag: "Chanteur folk tamoul (Gana)",
    region: "tamoul",
    featured: false,
    short: "Chanteur de folk urbain tamoul (Gana), connu pour ses morceaux festifs devenus viraux.",
    bio: [
      "Velmurugan s'est imposé comme l'une des voix populaires du style Gana, folk urbain originaire de Chennai, avec des morceaux festifs largement repris lors de mariages et de fêtes.",
    ],
    keyDates: ["2010s — Perce avec des morceaux Gana devenus viraux.", "2010s-2020s — Multiplie les collaborations dans le cinéma tamoul populaire."],
    latest: "Se produit régulièrement lors d'évènements populaires en Inde du Sud.",
  },
  {
    slug: "senthil-ganesh",
    image: "/artists/senthil-ganesh.jpg",
    icon: "drum",
    color: "from-amber-800 to-amber-600",
    name: "Senthil Ganesh",
    tag: "Chanteur folk tamoul (Gana)",
    region: "tamoul",
    featured: false,
    short: "L'un des chanteurs Gana (folk urbain de Chennai) les plus populaires, connu pour ses morceaux festifs viraux.",
    bio: [
      "Senthil Ganesh s'est fait connaître par des morceaux de style Gana devenus des hymnes populaires lors des célébrations en Inde du Sud, contribuant à la reconnaissance de ce genre au cinéma.",
    ],
    keyDates: ["2010s — Perce avec des titres Gana devenus viraux.", "2010s-2020s — Multiplie les apparitions dans des bandes originales du cinéma tamoul."],
    latest: "Se produit régulièrement lors d'évènements populaires en Inde du Sud.",
  },
  {
    slug: "dhanush",
    image: "/artists/dhanush.jpg",
    icon: "mic",
    color: "from-slate-700 to-slate-500",
    name: "Dhanush",
    tag: "Acteur/chanteur tamoul",
    region: "tamoul",
    featured: false,
    short: "Acteur tamoul également chanteur, auteur du titre mondialement viral « Why This Kolaveri Di ».",
    bio: [
      "Dhanush est avant tout une star du cinéma tamoul, mais son incursion dans la chanson avec « Why This Kolaveri Di » (2011) est devenue un phénomène viral mondial, l'une des premières chansons indiennes à devenir virale à cette échelle sur internet.",
    ],
    keyDates: ["2011 — Interprète « Why This Kolaveri Di », succès viral mondial.", "2010s-2020s — Poursuit une carrière de premier plan comme acteur du cinéma tamoul."],
    latest: "Reste actif principalement comme acteur et réalisateur, avec des apparitions ponctuelles en chant.",
  },
  {
    slug: "vijay-prakash",
    image: "/artists/vijay-prakash.jpg",
    icon: "mic",
    color: "from-orange-600 to-orange-400",
    name: "Vijay Prakash",
    tag: "Chanteur playback sud-indien",
    region: "tamoul",
    featured: false,
    short: "Chanteur de playback très polyvalent, actif dans le cinéma tamoul, kannada, télougou et hindi.",
    bio: [
      "Vijay Prakash s'est imposé par sa polyvalence entre chant classique carnatique et morceaux populaires, devenant l'une des voix masculines les plus demandées du cinéma sud-indien.",
    ],
    keyDates: ["2000s — Débute sa carrière de chanteur playback.", "2010s-2020s — Multiplie les récompenses régionales."],
    latest: "Se produit régulièrement en concert en Inde du Sud et à l'international.",
  },
  {
    slug: "saindhavi",
    image: "/artists/saindhavi.jpg",
    icon: "mic",
    color: "from-pink-700 to-pink-500",
    name: "Saindhavi",
    tag: "Chanteuse playback tamoule",
    region: "tamoul",
    featured: false,
    short: "Chanteuse de playback tamoule appréciée pour sa voix douce, active depuis le milieu des années 2000.",
    bio: [
      "Saindhavi s'est imposée dans le cinéma tamoul par des interprétations délicates de chansons romantiques et folkloriques, devenant une voix féminine régulière de l'industrie.",
    ],
    keyDates: ["2006 — Débute sa carrière de playback.", "2010s-2020s — Multiplie les collaborations avec les grands compositeurs tamouls."],
    latest: "Se produit régulièrement en concert en Inde du Sud.",
  },
];
