export type IconKey = "keys" | "mic" | "drum" | "headphones" | "note";
export type Region = "tamoul" | "hindi" | "telougou" | "punjabi" | "malayalam" | "classique";

export type Artist = {
  slug: string;
  image: string;
  icon: IconKey;
  color: string;
  name: string;
  tag: string;
  region: Region;
  featured: boolean;
  short: string;
  bio: string[];
  keyDates: string[];
  latest: string;
};

export const ARTISTS: Artist[] = [
  {
    slug: "ar-rahman",
    image: "/artists/ar-rahman.jpg",
    icon: "headphones",
    color: "from-blue-600 to-blue-400",
    name: "A.R. Rahman",
    tag: "Musique de film",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur oscarisé (Slumdog Millionaire), surnommé le « Mozart de Madras ». Ses concerts mêlent orchestre symphonique, musique électronique et sonorités traditionnelles indiennes.",
    bio: [
      "Né à Madras (aujourd'hui Chennai), A.R. Rahman s'impose dès les années 1990 comme l'un des compositeurs les plus innovants du cinéma indien, en mêlant instruments classiques indiens, chœurs, et production électronique moderne.",
      "Sa notoriété devient mondiale avec la bande originale de Slumdog Millionaire, récompensée de deux Oscars et de deux Grammy Awards. Il continue de composer pour le cinéma indien et international et donne régulièrement de grands concerts symphoniques à travers le monde.",
    ],
    keyDates: [
      "1992 — Débute au cinéma avec la bande originale du film Roja.",
      "1995 — Compose la musique du film Bombay, saluée internationalement.",
      "2008 — Remporte deux Oscars et deux Grammy Awards pour Slumdog Millionaire.",
    ],
    latest:
      "En tournée symphonique aux États-Unis en juillet 2026 (San Francisco Symphony le 2 juillet, Wolf Trap le 10 juillet, Houston Symphony les 24 et 25 juillet), avec d'autres dates prévues jusqu'en août.",
  },
  {
    slug: "arijit-singh",
    image: "/artists/arijit-singh.jpg",
    icon: "mic",
    color: "from-indigo-600 to-indigo-400",
    name: "Arijit Singh",
    tag: "Playback Bollywood",
    region: "hindi",
    featured: true,
    short:
      "L'une des voix les plus streamées d'Asie. Connu pour ses ballades romantiques dans le cinéma hindi, il remplit les plus grandes salles dès l'annonce d'une tournée.",
    bio: [
      "Révélé par une émission de télé-crochet, Arijit Singh devient en quelques années l'une des voix de playback les plus demandées de Bollywood, portée par un timbre chaud reconnaissable dès les premières notes.",
      "Il cumule des milliards d'écoutes en streaming et se produit régulièrement en tournée devant un public international, notamment auprès de la diaspora indienne en Europe, aux États-Unis et au Moyen-Orient.",
    ],
    keyDates: [
      "2013 — Révélation avec le titre « Tum Hi Ho » (Aashiqui 2), qui le propulse au premier plan.",
      "2010s — Multiplie les récompenses (Filmfare, IIFA) comme meilleur chanteur playback année après année.",
    ],
    latest:
      "A annoncé le 10 février 2026 à Mumbai un « World Tour 2026-27 » de 40 villes, son plus grand à ce jour, avec deux dates au DY Patil Stadium de Navi Mumbai les 15 et 16 mai 2026.",
  },
  {
    slug: "shreya-ghoshal",
    image: "/artists/shreya-ghoshal.jpg",
    icon: "mic",
    color: "from-sky-600 to-sky-400",
    name: "Shreya Ghoshal",
    tag: "Chant classique & Bollywood",
    region: "hindi",
    featured: true,
    short:
      "Voix emblématique du cinéma indien depuis plus de 20 ans, elle allie technique classique carnatique et pop moderne sur scène.",
    bio: [
      "Formée très jeune au chant classique, Shreya Ghoshal se fait connaître dès le début des années 2000 dans le cinéma hindi et devient rapidement l'une des chanteuses de playback les plus récompensées d'Inde.",
      "Sa voix polyvalente lui permet de naviguer entre mélodies classiques, chansons romantiques et morceaux dansants, ce qui en fait une valeur sûre des concerts en salle comme des grands festivals.",
    ],
    keyDates: [
      "2000 — Débute au cinéma hindi avec Devdas et se fait immédiatement remarquer.",
      "2000s-2010s — Multiplie les National Film Awards de la meilleure chanteuse playback.",
    ],
    latest:
      "En tournée mondiale avec « The Unstoppable Tour » (avril à septembre 2026) : Asie en juillet (Singapour, Kuala Lumpur, Bangkok), Auckland le 20 juin, puis Amérique du Nord en septembre.",
  },
  {
    slug: "zakir-hussain",
    image: "/artists/zakir-hussain.jpg",
    icon: "drum",
    color: "from-amber-600 to-amber-400",
    name: "Zakir Hussain",
    tag: "Percussions classiques",
    region: "classique",
    featured: true,
    short:
      "Maître du tabla reconnu mondialement, il a collaboré avec des artistes de jazz et de musique du monde tout en portant la tradition indienne sur les plus grandes scènes.",
    bio: [
      "Fils du légendaire joueur de tabla Ustad Alla Rakha, Zakir Hussain a perpétué et réinventé la tradition de la percussion classique indienne pendant plus de cinq décennies.",
      "Ses collaborations avec des musiciens de jazz, de musique du monde et de musique classique occidentale ont largement contribué à faire connaître le tabla hors d'Inde, sans jamais l'éloigner de ses racines. Il est décédé le 15 décembre 2024, laissant une œuvre considérable et de nombreux hommages dans le monde de la musique.",
    ],
    keyDates: [
      "Grammy Awards — Plusieurs récompenses au cours de sa carrière, dont trois lors de la cérémonie 2024 pour ses albums de musique du monde.",
      "15 décembre 2024 — Décès du maître, salué comme le plus grand joueur de tabla de sa génération.",
    ],
    latest:
      "Depuis sa disparition, ses proches et collaborateurs (notamment Third Coast Percussion) organisent des tournées hommage reprenant sa dernière œuvre, Murmurs in Time, sortie en EP le 7 février 2025.",
  },
  {
    slug: "anirudh-ravichander",
    image: "/artists/anirudh-ravichander.jpg",
    icon: "headphones",
    color: "from-teal-600 to-teal-400",
    name: "Anirudh Ravichander",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Figure incontournable du cinéma tamoul (Kollywood), connu pour ses bandes originales énergiques et ses concerts électrisants qui remplissent les stades en Inde du Sud.",
    bio: [
      "Repéré très jeune par le réalisateur Mani Ratnam, Anirudh Ravichander s'impose rapidement comme l'un des compositeurs les plus populaires du cinéma tamoul, avec un style qui mélange pop, hip-hop et sonorités électroniques.",
      "Ses tournées et concerts live, portés par une forte présence scénique, attirent un public massif en Inde du Sud comme au sein de la diaspora tamoule à l'international.",
    ],
    keyDates: [
      "2011 — Perce avec le titre viral « Why This Kolaveri Di » (film 3), succès national puis international.",
      "2010s-2020s — Devient l'un des compositeurs et interprètes tamouls les plus streamés.",
    ],
    latest:
      "En tournée « Anirudh XV Tour 2026 » : Dubaï le 11 janvier, Paris (Adidas Arena) le 18 avril, Trenton (New Jersey) le 30 août et Toronto le 5 septembre 2026.",
  },
  {
    slug: "harris-jayaraj",
    image: "/artists/harris-jayaraj.jpg",
    icon: "note",
    color: "from-violet-600 to-violet-400",
    name: "Harris Jayaraj",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur emblématique du cinéma tamoul depuis les années 2000, réputé pour ses mélodies romantiques et ses orchestrations soignées.",
    bio: [
      "Harris Jayaraj s'est fait connaître à la fin des années 1990 pour ses orchestrations riches et ses mélodies romantiques, devenant l'un des compositeurs de référence du cinéma tamoul.",
      "Son style, marqué par des arrangements soignés mêlant cordes, chœurs et sonorités contemporaines, a profondément influencé toute une génération de musique de film en Inde du Sud.",
    ],
    keyDates: [
      "1999 — Débute avec la bande originale du film Minnale, immédiatement remarquée.",
      "Années 2000 — Enchaîne les succès qui font de lui une référence du cinéma tamoul romantique.",
    ],
    latest:
      "A composé la musique de Kadhal Reset Repeat, comédie musicale romantique tamoule sortie en salles le 6 mars 2026.",
  },
  {
    slug: "yuvan-shankar-raja",
    image: "/artists/yuvan-shankar-raja.jpg",
    icon: "keys",
    color: "from-rose-600 to-rose-400",
    name: "Yuvan Shankar Raja",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: true,
    short:
      "Compositeur prolifique et polyvalent du cinéma tamoul, entre bandes originales pop, folk et musique de film, avec une large base de fans.",
    bio: [
      "Fils du compositeur Ilaiyaraaja, Yuvan Shankar Raja se forge sa propre identité musicale dès les années 1990 en explorant un large éventail de styles, du folk tamoul à la pop électronique.",
      "Réputé pour sa productivité et sa capacité à se réinventer, il reste l'un des compositeurs les plus sollicités du cinéma tamoul, avec une fanbase fidèle qui suit ses concerts avec ferveur.",
    ],
    keyDates: [
      "1997 — Débute comme compositeur à seulement 17 ans avec le film Aravindhan.",
      "2020s — Signe la bande originale du film à succès The Greatest of All Time.",
    ],
    latest:
      "Concert prévu le 4 juillet 2026 à l'Expo Ground de Pondichéry, après une tournée en Australie en 2025 (Sydney, Melbourne) et la sortie de l'album Jayam Ravi Hits le 8 septembre 2025.",
  },
  {
    slug: "ilaiyaraaja",
    image: "/artists/ilaiyaraaja.jpg",
    icon: "keys",
    color: "from-emerald-600 to-emerald-400",
    name: "Ilaiyaraaja",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Surnommé « l'Isai Gnani » (le sage de la musique), il a composé plus de 4 500 chansons et la musique de plus de 1 000 films en cinq décennies de carrière.",
    bio: [
      "Figure fondatrice de la musique de film tamoule moderne, Ilaiyaraaja a introduit dès la fin des années 1970 l'usage de l'orchestration occidentale mêlée aux ragas classiques indiens et aux mélodies folkloriques du Tamil Nadu.",
      "Père du compositeur Yuvan Shankar Raja, il reste actif sur scène avec de grandes tournées symphoniques rendant hommage à son répertoire, y compris à l'international.",
    ],
    keyDates: [
      "1976 — Débute comme compositeur avec le film Annakkili.",
      "Record du monde — Seul compositeur de l'histoire du cinéma à avoir signé la musique de plus de 1 000 films.",
    ],
    latest:
      "Tournée « Ilaiyaraaja Live 2026 » : concert à Chennai après une étape à Londres, puis dates au Royaume-Uni (OVO Arena Wembley le 10 juillet) et aux États-Unis (EagleBank Arena) dans le cadre du « Raja 50 USA Tour ».",
  },
  {
    slug: "gv-prakash-kumar",
    image: "/artists/gv-prakash-kumar.jpg",
    icon: "note",
    color: "from-cyan-600 to-cyan-400",
    name: "G.V. Prakash Kumar",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Neveu d'A.R. Rahman, il s'est imposé comme l'un des compositeurs les plus prolifiques du cinéma tamoul, avant de devenir aussi acteur.",
    bio: [
      "G.V. Prakash Kumar débute très jeune dans l'industrie du cinéma tamoul et se forge rapidement une identité musicale mêlant mélodies populaires et sonorités contemporaines.",
      "En parallèle de sa carrière de compositeur, il s'est également imposé comme acteur dans plusieurs films tamouls à succès.",
    ],
    keyDates: [
      "2006 — Débute comme compositeur avec le film Veyyil.",
      "Janvier 2026 — Compose la musique de Parasakthi, son 100e film en tant que compositeur.",
    ],
    latest:
      "A composé la musique de Parasakthi (sorti le 10 janvier 2026) et apparaît en tant qu'acteur dans Happy Raj, sorti le 27 mars 2026.",
  },
  {
    slug: "santhosh-narayanan",
    image: "/artists/santhosh-narayanan.jpg",
    icon: "headphones",
    color: "from-orange-600 to-orange-400",
    name: "Santhosh Narayanan",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Compositeur tamoul à l'univers sonore singulier, mêlant folk du Tamil Nadu, hip-hop et musique électronique indépendante.",
    bio: [
      "Repéré grâce à sa collaboration avec le réalisateur Pa. Ranjith, Santhosh Narayanan s'est distingué par des bandes originales ancrées dans les musiques populaires et folkloriques tamoules, avec une touche résolument moderne.",
      "Il collabore aussi régulièrement avec des artistes internationaux, contribuant à faire connaître la scène musicale tamoule indépendante hors d'Inde.",
    ],
    keyDates: [
      "2012 — Révélé par la bande originale du film Attakathi.",
      "Octobre 2025 — Collabore avec Ed Sheeran sur l'EP Play (The Remixes).",
    ],
    latest:
      "A composé la musique du film Vaa Vaathiyaar, sorti le 14 janvier 2026, et a produit le single « Vari Vari » de la chanteuse Dhee en 2026.",
  },
  {
    slug: "sid-sriram",
    image: "/artists/sid-sriram.jpg",
    icon: "mic",
    color: "from-fuchsia-600 to-fuchsia-400",
    name: "Sid Sriram",
    tag: "Chanteur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Chanteur né en Inde et formé aux États-Unis, il marie musique carnatique traditionnelle et pop/R&B contemporains, aussi bien dans le cinéma tamoul qu'en tant qu'artiste solo.",
    bio: [
      "Formé dès l'enfance à la musique carnatique puis élevé en Californie, Sid Sriram développe un style unique mêlant tradition indienne et influences R&B et hip-hop américaines.",
      "Très demandé comme chanteur playback dans le cinéma tamoul, il mène en parallèle une carrière solo internationale, avec des collaborations remarquées dans l'industrie musicale américaine.",
    ],
    keyDates: [
      "2012 — Débute comme chanteur playback dans le cinéma tamoul.",
      "2023 — Sort Sidharth, son premier album entièrement en anglais, chez Def Jam.",
    ],
    latest:
      "Tournée nord-américaine à l'automne 2026, avec des dates en septembre (Illinois, New Jersey, Virginie, Washington, Californie) et des concerts au Blue Note de New York et Los Angeles en novembre 2026.",
  },
  {
    slug: "d-imman",
    image: "/artists/d-imman.jpg",
    icon: "note",
    color: "from-lime-600 to-lime-400",
    name: "D. Imman",
    tag: "Compositeur tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Compositeur tamoul réputé pour ses mélodies mélodieuses et ses bandes originales rurales, récompensé à plusieurs reprises pour son travail dans le cinéma tamoul.",
    bio: [
      "D. Imman se distingue par des compositions mélodiques marquées par des sonorités folkloriques et rurales, très appréciées dans le cinéma tamoul populaire.",
      "Il a composé la musique de nombreux films à succès et reste l'un des compositeurs les plus actifs de l'industrie, avec plusieurs sorties chaque année.",
    ],
    keyDates: [
      "2008 — Débute avec la bande originale du film Vil Ambu.",
      "2010s — Multiplie les récompenses pour ses bandes originales dans le cinéma tamoul.",
    ],
    latest:
      "A composé la musique du film Vadam, sorti le 6 mars 2026, ainsi que celle de plusieurs autres sorties tamoules de l'année.",
  },
  {
    slug: "hiphop-tamizha",
    image: "/artists/hiphop-tamizha.jpg",
    icon: "headphones",
    color: "from-red-600 to-red-400",
    name: "Hiphop Tamizha (Adhi)",
    tag: "Duo hip-hop tamoul",
    region: "tamoul",
    featured: false,
    short:
      "Duo formé d'Adhi et Jeeva, pionnier du hip-hop en langue tamoule, connu pour ses titres énergiques et ses concerts très suivis en Inde du Sud.",
    bio: [
      "Basé à Chennai, le duo Hiphop Tamizha est considéré comme le pionnier du hip-hop en tamoul, mêlant rap, pop et sonorités traditionnelles dans des morceaux devenus des hymnes populaires.",
      "Adhi, la voix et le compositeur principal du duo, s'est aussi imposé comme acteur et réalisateur dans le cinéma tamoul.",
    ],
    keyDates: [
      "2014 — Premier album qui installe le duo comme pionnier du hip-hop tamoul.",
      "Plusieurs titres devenus viraux, dont « Ethir Neechal » et « Sakkarakatti ».",
    ],
    latest:
      "Concert prévu le 7 mars 2026 au YMCA Ground de Chennai ; pas de tournée internationale annoncée pour le moment.",
  },
  {
    slug: "dhee",
    image: "/artists/dhee.jpg",
    icon: "mic",
    color: "from-pink-600 to-pink-400",
    name: "Dhee",
    tag: "Chanteuse tamoule",
    region: "tamoul",
    featured: false,
    short:
      "Révélée par le titre viral « Rowdy Baby », elle s'impose depuis comme l'une des voix montantes de la pop tamoule contemporaine.",
    bio: [
      "Dhee se fait connaître en 2018 avec « Rowdy Baby » (film Maari 2, avec Yuvan Shankar Raja), devenu l'une des vidéos musicales indiennes les plus vues au monde.",
      "Depuis, elle poursuit une carrière solo entre pop tamoule et collaborations internationales, en explorant des sonorités plus électroniques et personnelles.",
    ],
    keyDates: [
      "2018 — Explose avec « Rowdy Baby », plus d'1,5 milliard de vues sur YouTube.",
      "Octobre 2025 — Apparaît sur l'EP Play (The Remixes) d'Ed Sheeran.",
    ],
    latest:
      "A sorti plusieurs nouveaux titres en 2026, dont « Like I Want You » (13 mars 2026) et le single « Vari Vari », produit par Santhosh Narayanan.",
  },
  {
    slug: "chinmayi-sripada",
    image: "/artists/chinmayi-sripada.jpg",
    icon: "mic",
    color: "from-purple-600 to-purple-400",
    name: "Chinmayi Sripada",
    tag: "Chanteuse tamoule",
    region: "tamoul",
    featured: false,
    short:
      "Chanteuse et actrice de doublage prolifique, active dans le cinéma tamoul, télougou, kannada, malayalam et hindi depuis plus de 20 ans.",
    bio: [
      "Chinmayi Sripada s'est imposée dès les années 2000 comme l'une des chanteuses de playback les plus polyvalentes du sud de l'Inde, avant de développer également une importante carrière de doublage.",
      "Elle poursuit aujourd'hui ses activités de chanteuse et de doubleuse dans plusieurs langues, tout en étant également entrepreneuse.",
    ],
    keyDates: [
      "2001 — Débute comme chanteuse playback dans le cinéma tamoul.",
      "2023 — Fait son retour au doublage dans le cinéma tamoul après plusieurs années d'absence.",
    ],
    latest:
      "A prêté sa voix dans le film Karuppu (2026) et a doublé pour le film télougou Dacoit: A Love Story en 2026.",
  },

  // --- Légendes et grands noms de la musique de film hindi (Bollywood) ---
  {
    slug: "lata-mangeshkar",
    image: "/artists/lata-mangeshkar.jpg",
    icon: "mic",
    color: "from-slate-600 to-slate-400",
    name: "Lata Mangeshkar",
    tag: "Légende du playback hindi",
    region: "hindi",
    featured: false,
    short: "Surnommée « le Rossignol de l'Inde », elle a marqué sept décennies de cinéma indien.",
    bio: [
      "Considérée comme l'une des plus grandes voix de l'histoire du cinéma indien, Lata Mangeshkar a enregistré des milliers de chansons dans de nombreuses langues à partir des années 1940.",
    ],
    keyDates: ["Années 1940 — Débute sa carrière de playback.", "6 février 2022 — Décès, suivi d'un deuil national en Inde."],
    latest: "Décédée en 2022, elle reste célébrée chaque année lors d'hommages et de concerts en son honneur en Inde.",
  },
  {
    slug: "kishore-kumar",
    image: "/artists/kishore-kumar.jpg",
    icon: "mic",
    color: "from-stone-600 to-stone-400",
    name: "Kishore Kumar",
    tag: "Légende du playback hindi",
    region: "hindi",
    featured: false,
    short: "Chanteur et acteur emblématique, à la voix reconnaissable entre toutes, star du cinéma hindi des années 1970-80.",
    bio: [
      "Kishore Kumar a marqué le cinéma hindi par sa polyvalence, entre comédie, drame et chant, devenant l'une des voix de playback les plus populaires de sa génération.",
    ],
    keyDates: ["Années 1970-80 — Sommet de sa popularité comme chanteur et acteur.", "13 octobre 1987 — Décès."],
    latest: "Son répertoire continue d'être repris régulièrement lors de concerts hommage en Inde et dans la diaspora.",
  },
  {
    slug: "mohammed-rafi",
    image: "/artists/mohammed-rafi.jpg",
    icon: "mic",
    color: "from-neutral-600 to-neutral-400",
    name: "Mohammed Rafi",
    tag: "Légende du playback hindi",
    region: "hindi",
    featured: false,
    short: "L'une des voix fondatrices du playback hindi, active des années 1940 aux années 1980.",
    bio: [
      "Mohammed Rafi a prêté sa voix à des milliers de chansons de films hindi pendant plus de trois décennies, couvrant tous les registres, du romantique au dévotionnel.",
    ],
    keyDates: ["Années 1940 — Débute sa carrière.", "31 juillet 1980 — Décès."],
    latest: "Son héritage musical continue d'être célébré lors de nombreux concerts hommage en Inde.",
  },
  {
    slug: "asha-bhosle",
    image: "/artists/asha-bhosle.jpg",
    icon: "mic",
    color: "from-amber-700 to-amber-500",
    name: "Asha Bhosle",
    tag: "Chanteuse playback hindi",
    region: "hindi",
    featured: false,
    short: "Sœur de Lata Mangeshkar et immense voix du playback hindi, connue pour sa polyvalence entre cabaret, pop et musique classique.",
    bio: [
      "Asha Bhosle a exploré des styles très variés au fil de sa carrière, des chansons de cabaret aux fusions électroniques, tout en restant l'une des voix les plus respectées du cinéma indien.",
    ],
    keyDates: ["Années 1940 — Débute sa carrière.", "Record Guinness pour le nombre de chansons enregistrées par une même artiste."],
    latest: "Toujours active ponctuellement pour des apparitions publiques ; consultez les plateformes de billetterie pour ses éventuelles dates 2026.",
  },
  {
    slug: "rd-burman",
    image: "/artists/rd-burman.jpg",
    icon: "keys",
    color: "from-yellow-700 to-yellow-500",
    name: "R.D. Burman",
    tag: "Compositeur hindi",
    region: "hindi",
    featured: false,
    short: "Compositeur emblématique du cinéma hindi des années 1970-80, précurseur de la fusion pop-orchestrale en Inde.",
    bio: [
      "R.D. Burman a révolutionné la musique de film hindi en y intégrant des sonorités funk, rock et électroniques, influençant durablement la génération de compositeurs suivante.",
    ],
    keyDates: ["Années 1960-70 — Devient l'un des compositeurs les plus demandés de Bollywood.", "4 janvier 1994 — Décès."],
    latest: "Son influence reste célébrée lors de nombreux concerts hommage consacrés à son répertoire.",
  },
  {
    slug: "sonu-nigam",
    image: "/artists/sonu-nigam.jpg",
    icon: "mic",
    color: "from-blue-700 to-blue-500",
    name: "Sonu Nigam",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "L'une des voix les plus polyvalentes du cinéma hindi depuis les années 1990, également animateur télé reconnu.",
    bio: [
      "Sonu Nigam s'est imposé dans les années 1990 comme un chanteur de playback majeur du cinéma hindi, avant d'élargir sa carrière à la télévision et aux concerts internationaux.",
    ],
    keyDates: ["1990s — Perce dans le cinéma hindi.", "2000s — Multiplie tournées internationales et récompenses."],
    latest: "Continue de se produire régulièrement en Inde et à l'international ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "shaan",
    image: "/artists/shaan.jpg",
    icon: "mic",
    color: "from-indigo-700 to-indigo-500",
    name: "Shaan",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "Chanteur pop et playback populaire depuis les années 1990, connu pour ses ballades romantiques.",
    bio: [
      "Shaan s'est fait connaître avec des tubes pop indépendants avant de devenir l'une des voix régulières du cinéma hindi dans les années 2000.",
    ],
    keyDates: ["1990s — Débuts dans la pop indi-pop.", "2000s — Multiplie les chansons à succès dans le cinéma hindi."],
    latest: "Se produit régulièrement en Inde et à l'étranger ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "sunidhi-chauhan",
    image: "/artists/sunidhi-chauhan.jpg",
    icon: "mic",
    color: "from-rose-700 to-rose-500",
    name: "Sunidhi Chauhan",
    tag: "Chanteuse playback hindi",
    region: "hindi",
    featured: false,
    short: "Révélée enfant à la télévision, elle est devenue l'une des voix les plus dynamiques du cinéma hindi.",
    bio: [
      "Sunidhi Chauhan s'impose depuis la fin des années 1990 par sa polyvalence, entre chansons dansantes énergiques et ballades, et par une forte présence scénique en concert.",
    ],
    keyDates: ["1996 — Débute au cinéma hindi.", "2000s-2010s — Multiplie les récompenses nationales."],
    latest: "Continue de tourner régulièrement en Inde et à l'international ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "alka-yagnik",
    image: "/artists/alka-yagnik.jpg",
    icon: "mic",
    color: "from-pink-700 to-pink-500",
    name: "Alka Yagnik",
    tag: "Chanteuse playback hindi",
    region: "hindi",
    featured: false,
    short: "L'une des chanteuses de playback les plus prolifiques des années 1980 à 2000 dans le cinéma hindi.",
    bio: [
      "Alka Yagnik a enregistré des milliers de chansons pour le cinéma hindi, dominant les classements musicaux pendant plus de deux décennies.",
    ],
    keyDates: ["1980s — Débute sa carrière.", "1990s-2000s — Devient l'une des voix les plus streamées du cinéma hindi."],
    latest: "Reste active sur la scène musicale indienne ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "kumar-sanu",
    image: "/artists/kumar-sanu.jpg",
    icon: "mic",
    color: "from-orange-700 to-orange-500",
    name: "Kumar Sanu",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "Voix dominante du cinéma hindi dans les années 1990, détenteur de plusieurs records de Filmfare Awards consécutifs.",
    bio: [
      "Kumar Sanu a marqué la décennie 1990 par une omniprésence rare dans les bandes originales du cinéma hindi, remportant le Filmfare Award du meilleur chanteur playback cinq années de suite.",
    ],
    keyDates: ["1989 — Débute sa carrière au cinéma hindi.", "1990s — Remporte cinq Filmfare Awards consécutifs."],
    latest: "Continue de se produire lors de concerts nostalgie consacrés aux années 1990.",
  },
  {
    slug: "udit-narayan",
    image: "/artists/udit-narayan.jpg",
    icon: "mic",
    color: "from-teal-700 to-teal-500",
    name: "Udit Narayan",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "Voix incontournable du cinéma hindi des années 1980 à 2000, connu pour ses chansons romantiques.",
    bio: [
      "Udit Narayan s'est imposé comme l'une des voix masculines les plus populaires du cinéma hindi, notamment pour les rôles de jeunes premiers dans les années 1990.",
    ],
    keyDates: ["1980s — Débute sa carrière.", "1990s-2000s — Multiplie les National Film Awards."],
    latest: "Continue de se produire en Inde et à l'international ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "kk",
    image: "/artists/kk.jpg",
    icon: "mic",
    color: "from-cyan-700 to-cyan-500",
    name: "KK (Krishnakumar Kunnath)",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "Chanteur très apprécié pour sa voix chaleureuse et ses ballades, star des années 2000.",
    bio: [
      "KK s'est distingué par des interprétations intenses et sincères, devenant l'une des voix préférées du public pour les chansons romantiques et mélancoliques du cinéma hindi.",
    ],
    keyDates: ["1999 — Sort son premier album solo, Pal.", "31 mai 2022 — Décès peu après un concert à Calcutta."],
    latest: "Sa disparition en 2022, survenue peu après un concert, a suscité une immense émotion en Inde ; son répertoire continue d'être célébré lors d'hommages.",
  },
  {
    slug: "neha-kakkar",
    image: "/artists/neha-kakkar.jpg",
    icon: "mic",
    color: "from-fuchsia-700 to-fuchsia-500",
    name: "Neha Kakkar",
    tag: "Chanteuse pop/playback hindi",
    region: "hindi",
    featured: false,
    short: "Chanteuse pop très populaire sur les réseaux sociaux et jury de télé-crochets, star de la scène hindi contemporaine.",
    bio: [
      "Neha Kakkar s'est fait connaître via les réseaux sociaux et la télévision avant de devenir l'une des chanteuses les plus streamées du cinéma hindi actuel.",
    ],
    keyDates: ["2016 — Enchaîne les tubes viraux dans le cinéma hindi.", "2020s — S'impose comme jury de télé-crochets musicaux."],
    latest: "Reste très active sur les réseaux et en concerts ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "jubin-nautiyal",
    image: "/artists/jubin-nautiyal.jpg",
    icon: "mic",
    color: "from-violet-700 to-violet-500",
    name: "Jubin Nautiyal",
    tag: "Chanteur playback hindi",
    region: "hindi",
    featured: false,
    short: "L'une des voix montantes du playback hindi de la décennie 2010-2020, réputé pour ses ballades romantiques.",
    bio: [
      "Jubin Nautiyal s'est imposé dans les années 2010 comme l'une des voix les plus streamées de Bollywood, en particulier sur les chansons d'amour.",
    ],
    keyDates: ["2014 — Perce dans le cinéma hindi.", "2020s — Multiplie les titres à plusieurs centaines de millions d'écoutes."],
    latest: "Se produit régulièrement en Inde et dans la diaspora ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "armaan-malik",
    image: "/artists/armaan-malik.jpg",
    icon: "mic",
    color: "from-red-700 to-red-500",
    name: "Armaan Malik",
    tag: "Chanteur pop/playback hindi",
    region: "hindi",
    featured: false,
    short: "Chanteur précoce devenu star du playback hindi, avec une carrière internationale en développement.",
    bio: [
      "Armaan Malik a commencé très jeune dans le cinéma hindi avant de développer une carrière pop internationale, avec des collaborations en anglais.",
    ],
    keyDates: ["2011 — Débute au cinéma hindi encore adolescent.", "2018 — Sort de la musique en anglais pour un public international."],
    latest: "Poursuit une carrière entre Inde et scène internationale ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "pritam",
    image: "/artists/pritam.jpg",
    icon: "keys",
    color: "from-emerald-700 to-emerald-500",
    name: "Pritam",
    tag: "Compositeur hindi",
    region: "hindi",
    featured: false,
    short: "L'un des compositeurs les plus prolifiques et populaires du cinéma hindi contemporain.",
    bio: [
      "Pritam s'est imposé dans les années 2000 comme un compositeur incontournable de Bollywood, capable de naviguer entre pop dansante, ballades et musique de film indépendante.",
    ],
    keyDates: ["2002 — Perce dans le cinéma hindi.", "2010s-2020s — Compose plusieurs des plus grands succès musicaux de Bollywood."],
    latest: "Continue de composer pour de grandes productions hindi chaque année.",
  },
  {
    slug: "amit-trivedi",
    image: "/artists/amit-trivedi.jpg",
    icon: "keys",
    color: "from-sky-700 to-sky-500",
    name: "Amit Trivedi",
    tag: "Compositeur hindi",
    region: "hindi",
    featured: false,
    short: "Compositeur réputé pour son style indépendant et alternatif, distinct des formules classiques de Bollywood.",
    bio: [
      "Amit Trivedi s'est fait connaître grâce à des bandes originales audacieuses mêlant folk indien et sonorités alternatives, s'imposant comme une voix singulière du cinéma hindi.",
    ],
    keyDates: ["2009 — Révélé par la bande originale du film Dev D.", "2010s-2020s — Multiplie les collaborations avec le cinéma d'auteur hindi."],
    latest: "Continue de composer pour le cinéma hindi et se produit occasionnellement en concert.",
  },
  {
    slug: "vishal-shekhar",
    image: "/artists/vishal-shekhar.jpg",
    icon: "keys",
    color: "from-lime-700 to-lime-500",
    name: "Vishal-Shekhar",
    tag: "Duo de compositeurs hindi",
    region: "hindi",
    featured: false,
    short: "Duo de compositeurs (Vishal Dadlani et Shekhar Ravjiani) parmi les plus populaires du cinéma hindi depuis les années 2000.",
    bio: [
      "Vishal-Shekhar se sont imposés comme l'un des duos de compositeurs les plus demandés de Bollywood, avec un style énergique mêlant pop, électro et orchestrations modernes.",
    ],
    keyDates: ["2001 — Débute avec le film Jhankaar Beats.", "2010s — Signent plusieurs bandes originales parmi les plus streamées de Bollywood."],
    latest: "Continuent de composer pour de grandes productions hindi et de se produire en tournée.",
  },
  {
    slug: "shankar-ehsaan-loy",
    image: "/artists/shankar-ehsaan-loy.jpg",
    icon: "keys",
    color: "from-amber-800 to-amber-600",
    name: "Shankar-Ehsaan-Loy",
    tag: "Trio de compositeurs hindi",
    region: "hindi",
    featured: false,
    short: "Trio de compositeurs parmi les plus respectés du cinéma hindi depuis la fin des années 1990.",
    bio: [
      "Shankar-Ehsaan-Loy ont marqué le cinéma hindi par des bandes originales devenues cultes, mêlant orchestrations riches, rock et musique traditionnelle indienne.",
    ],
    keyDates: ["1999 — Révélés par la bande originale de Dil Chahta Hai.", "2000s-2020s — Multiplient les collaborations avec les plus grands réalisateurs hindi."],
    latest: "Continuent de composer pour le cinéma hindi et se produisent régulièrement en concert symphonique.",
  },
  {
    slug: "badshah",
    image: "/artists/badshah.jpg",
    icon: "headphones",
    color: "from-zinc-700 to-zinc-500",
    name: "Badshah",
    tag: "Rappeur hindi",
    region: "hindi",
    featured: false,
    short: "L'un des rappeurs les plus populaires d'Inde, connu pour ses tubes festifs et dansants.",
    bio: [
      "Badshah s'est imposé dans les années 2010 comme une figure majeure du hip-hop hindi, avec des morceaux festifs devenus des hymnes de mariage et de soirée en Inde.",
    ],
    keyDates: ["2012 — Débuts en solo après ses débuts en groupe.", "2010s-2020s — Enchaîne les tubes viraux."],
    latest: "Continue de sortir des singles et de se produire en concert ; consultez les plateformes de billetterie pour ses dates 2026.",
  },

  // --- Scène punjabi ---
  {
    slug: "diljit-dosanjh",
    image: "/artists/diljit-dosanjh.jpg",
    icon: "mic",
    color: "from-orange-600 to-orange-400",
    name: "Diljit Dosanjh",
    tag: "Chanteur/acteur punjabi",
    region: "punjabi",
    featured: false,
    short: "Star de la pop punjabi devenue phénomène international, premier artiste punjabi à se produire à Coachella.",
    bio: [
      "Diljit Dosanjh a porté la musique punjabi sur la scène internationale, entre pop, hip-hop et sonorités traditionnelles, tout en menant une carrière d'acteur remarquée en Inde.",
    ],
    keyDates: ["2004 — Débute sa carrière musicale.", "2023 — Devient le premier artiste punjabi à se produire à Coachella."],
    latest: "Multiplie les tournées internationales ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "guru-randhawa",
    image: "/artists/guru-randhawa.jpg",
    icon: "mic",
    color: "from-red-600 to-red-400",
    name: "Guru Randhawa",
    tag: "Chanteur pop punjabi",
    region: "punjabi",
    featured: false,
    short: "L'un des artistes pop punjabi les plus streamés, connu pour ses tubes dansants.",
    bio: [
      "Guru Randhawa s'est imposé dans les années 2010 comme une figure incontournable de la pop punjabi, avec des morceaux cumulant des milliards de vues en ligne.",
    ],
    keyDates: ["2013 — Débute sa carrière solo.", "2017 — Perce à l'international avec « Lahore »."],
    latest: "Continue de tourner régulièrement à l'international ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "ap-dhillon",
    image: "/artists/ap-dhillon.jpg",
    icon: "headphones",
    color: "from-slate-700 to-slate-500",
    name: "AP Dhillon",
    tag: "Chanteur punjabi",
    region: "punjabi",
    featured: false,
    short: "Artiste punjabi-canadien à l'esthétique moderne, devenu une référence de la nouvelle scène punjabi internationale.",
    bio: [
      "AP Dhillon a contribué à moderniser la pop punjabi avec une production proche du R&B et de la trap occidentale, touchant un public jeune international.",
    ],
    keyDates: ["2020 — Perce avec le titre « Excuses ».", "2020s — Multiplie les collaborations internationales."],
    latest: "En tournée régulière en Amérique du Nord et en Europe ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "karan-aujla",
    image: "/artists/karan-aujla.jpg",
    icon: "mic",
    color: "from-yellow-600 to-yellow-400",
    name: "Karan Aujla",
    tag: "Chanteur punjabi",
    region: "punjabi",
    featured: false,
    short: "L'un des artistes punjabi les plus streamés de la nouvelle génération, entre rap et pop.",
    bio: [
      "Karan Aujla s'est imposé dans les années 2020 comme l'une des voix montantes les plus populaires de la scène punjabi, en Inde comme au sein de la diaspora.",
    ],
    keyDates: ["2018 — Débute sa carrière musicale.", "2020s — Multiplie les tubes viraux et tournées internationales."],
    latest: "En tournée internationale régulière ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "sidhu-moose-wala",
    image: "/artists/sidhu-moose-wala.jpg",
    icon: "mic",
    color: "from-gray-700 to-gray-500",
    name: "Sidhu Moose Wala",
    tag: "Chanteur/rappeur punjabi",
    region: "punjabi",
    featured: false,
    short: "Figure majeure du rap punjabi des années 2010-2020, disparu prématurément en 2022.",
    bio: [
      "Sidhu Moose Wala s'était imposé comme l'une des voix les plus influentes du rap punjabi, mêlant récits personnels et affirmation culturelle. Il est décédé le 29 mai 2022, une disparition qui a profondément marqué la scène musicale punjabi.",
    ],
    keyDates: ["2017 — Débute sa carrière musicale.", "29 mai 2022 — Décès."],
    latest: "Des titres inédits continuent d'être publiés à titre posthume par sa famille et son label.",
  },
  {
    slug: "b-praak",
    image: "/artists/b-praak.jpg",
    icon: "mic",
    color: "from-blue-600 to-blue-400",
    name: "B Praak",
    tag: "Chanteur/compositeur punjabi",
    region: "punjabi",
    featured: false,
    short: "Chanteur et compositeur punjabi connu pour ses ballades intenses, notamment « Filhaal ».",
    bio: [
      "B Praak s'est fait connaître par des interprétations vocales puissantes, en particulier sur des ballades dramatiques devenues virales en Inde et dans la diaspora punjabi.",
    ],
    keyDates: ["2018 — Perce avec le titre « Filhaal ».", "2020s — Multiplie les tournées internationales."],
    latest: "En tournée régulière en Inde et à l'international ; consultez les plateformes de billetterie pour ses dates 2026.",
  },

  // --- Autres légendes et voix du Sud de l'Inde ---
  {
    slug: "sp-balasubrahmanyam",
    image: "/artists/sp-balasubrahmanyam.jpg",
    icon: "mic",
    color: "from-teal-700 to-teal-500",
    name: "S.P. Balasubrahmanyam",
    tag: "Légende du playback sud-indien",
    region: "tamoul",
    featured: false,
    short: "Détenteur d'un record du monde pour le nombre de chansons enregistrées, figure la plus emblématique du playback sud-indien.",
    bio: [
      "S.P. Balasubrahmanyam a marqué le cinéma tamoul, télougou, kannada et hindi par une carrière de plus de quatre décennies, enregistrant des dizaines de milliers de chansons dans une quinzaine de langues. Il est décédé le 25 septembre 2020 des suites de la COVID-19.",
    ],
    keyDates: ["1966 — Débute sa carrière de playback.", "25 septembre 2020 — Décès."],
    latest: "Son héritage est célébré chaque année lors de nombreux concerts hommage à travers l'Inde du Sud.",
  },
  {
    slug: "ks-chithra",
    image: "/artists/ks-chithra.jpg",
    icon: "mic",
    color: "from-purple-700 to-purple-500",
    name: "K.S. Chithra",
    tag: "Chanteuse playback sud-indienne",
    region: "tamoul",
    featured: false,
    short: "L'une des chanteuses de playback les plus récompensées du Sud de l'Inde, active depuis les années 1980.",
    bio: [
      "K.S. Chithra a marqué le cinéma tamoul, malayalam et télougou par une voix versatile, remportant de nombreux National Film Awards au cours de sa carrière.",
    ],
    keyDates: ["1979 — Débute sa carrière.", "1980s-2000s — Multiplie les National Film Awards de la meilleure chanteuse playback."],
    latest: "Reste active en concert dans le Sud de l'Inde et au sein de la diaspora.",
  },
  {
    slug: "karthik",
    image: "/artists/karthik.jpg",
    icon: "mic",
    color: "from-cyan-600 to-cyan-400",
    name: "Karthik",
    tag: "Chanteur playback tamoul",
    region: "tamoul",
    featured: false,
    short: "Chanteur de playback tamoul très populaire dans les années 2000-2010, connu pour ses ballades romantiques.",
    bio: [
      "Karthik s'est imposé dans le cinéma tamoul par des interprétations intenses de chansons d'amour, devenant l'une des voix masculines les plus demandées de sa génération.",
    ],
    keyDates: ["2003 — Perce dans le cinéma tamoul.", "2010s — Multiplie les tubes romantiques au cinéma."],
    latest: "Se produit régulièrement en concert en Inde du Sud et à l'international.",
  },
  {
    slug: "vijay-yesudas",
    image: "/artists/vijay-yesudas.jpg",
    icon: "mic",
    color: "from-green-700 to-green-500",
    name: "Vijay Yesudas",
    tag: "Chanteur playback sud-indien",
    region: "tamoul",
    featured: false,
    short: "Fils de la légende K.J. Yesudas, il s'est forgé sa propre carrière de chanteur playback dans le Sud de l'Inde.",
    bio: [
      "Vijay Yesudas a construit une carrière remarquée dans le cinéma tamoul et malayalam, saluée par plusieurs récompenses nationales et régionales.",
    ],
    keyDates: ["2004 — Débute sa carrière de playback.", "2010s — Multiplie les récompenses régionales."],
    latest: "Se produit régulièrement en concert dans le Sud de l'Inde.",
  },
  {
    slug: "shweta-mohan",
    image: "/artists/shweta-mohan.jpg",
    icon: "mic",
    color: "from-rose-600 to-rose-400",
    name: "Shweta Mohan",
    tag: "Chanteuse playback sud-indienne",
    region: "tamoul",
    featured: false,
    short: "Chanteuse de playback active dans le cinéma tamoul et malayalam depuis le début des années 2000.",
    bio: [
      "Shweta Mohan s'est imposée comme l'une des voix féminines régulières du cinéma sud-indien, appréciée pour sa polyvalence entre mélodies douces et morceaux dansants.",
    ],
    keyDates: ["2003 — Débute sa carrière de playback.", "2010s-2020s — Multiplie les collaborations avec les grands compositeurs du Sud."],
    latest: "Se produit régulièrement en concert en Inde du Sud et au sein de la diaspora.",
  },

  // --- Telugu (Tollywood) ---
  {
    slug: "mm-keeravani",
    image: "/artists/mm-keeravani.jpg",
    icon: "keys",
    color: "from-amber-600 to-amber-400",
    name: "M.M. Keeravani",
    tag: "Compositeur télougou",
    region: "telougou",
    featured: false,
    short: "Compositeur télougou oscarisé pour « Naatu Naatu » (RRR), premier titre indien à remporter l'Oscar de la meilleure chanson.",
    bio: [
      "M.M. Keeravani compose pour le cinéma télougou depuis la fin des années 1980 et a acquis une reconnaissance mondiale grâce au film RRR, dont la chanson « Naatu Naatu » a remporté l'Oscar en 2023.",
    ],
    keyDates: ["1990 — Débute sa carrière de compositeur.", "2023 — Remporte l'Oscar de la meilleure chanson pour « Naatu Naatu » (RRR)."],
    latest: "Continue de composer pour de grandes productions télougoues et se produit occasionnellement en concert symphonique.",
  },
  {
    slug: "devi-sri-prasad",
    image: "/artists/devi-sri-prasad.jpg",
    icon: "headphones",
    color: "from-orange-500 to-orange-300",
    name: "Devi Sri Prasad",
    tag: "Compositeur télougou",
    region: "telougou",
    featured: false,
    short: "L'un des compositeurs les plus populaires du cinéma télougou, connu pour ses morceaux festifs (dont la saga Pushpa).",
    bio: [
      "Devi Sri Prasad (DSP) s'est imposé comme une valeur sûre du cinéma télougou grâce à des bandes originales énergiques mêlant folk du Sud de l'Inde et sonorités électroniques modernes.",
    ],
    keyDates: ["1998 — Débute sa carrière de compositeur.", "2020s — Compose plusieurs titres viraux de la saga Pushpa."],
    latest: "Continue de composer pour de grandes productions télougoues et donne régulièrement des concerts live.",
  },
  {
    slug: "thaman-s",
    image: "/artists/thaman-s.jpg",
    icon: "headphones",
    color: "from-red-500 to-red-300",
    name: "Thaman S",
    tag: "Compositeur télougou",
    region: "telougou",
    featured: false,
    short: "Compositeur télougou extrêmement prolifique, l'un des plus demandés de l'industrie Tollywood actuelle.",
    bio: [
      "Thaman S a bâti sa réputation sur des bandes originales percutantes et un rythme de production très soutenu, devenant l'un des compositeurs incontournables du cinéma télougou contemporain.",
    ],
    keyDates: ["2007 — Débute sa carrière de compositeur.", "2010s-2020s — Devient l'un des compositeurs les plus prolifiques de Tollywood."],
    latest: "Continue de composer pour de nombreuses sorties télougoues chaque année.",
  },

  // --- Malayalam ---
  {
    slug: "m-jayachandran",
    image: "/artists/m-jayachandran.jpg",
    icon: "keys",
    color: "from-emerald-600 to-emerald-400",
    name: "M. Jayachandran",
    tag: "Compositeur malayalam",
    region: "malayalam",
    featured: false,
    short: "Compositeur malayalam réputé pour ses mélodies raffinées, plusieurs fois récompensé aux National Film Awards.",
    bio: [
      "M. Jayachandran s'est imposé comme l'un des compositeurs les plus respectés du cinéma malayalam, connu pour des mélodies mêlant tradition carnatique et musique de film moderne.",
    ],
    keyDates: ["1988 — Débute sa carrière de compositeur.", "2010s — Multiplie les National Film Awards de la meilleure musique."],
    latest: "Continue de composer pour le cinéma malayalam et se produit occasionnellement en concert.",
  },
  {
    slug: "kj-yesudas",
    image: "/artists/kj-yesudas.jpg",
    icon: "mic",
    color: "from-green-600 to-green-400",
    name: "K.J. Yesudas",
    tag: "Légende du playback sud-indien",
    region: "malayalam",
    featured: false,
    short: "Surnommé « Gaanagandharvan », il est l'une des voix les plus vénérées du cinéma et de la musique classique indiens.",
    bio: [
      "K.J. Yesudas a enregistré des dizaines de milliers de chansons dans de nombreuses langues indiennes depuis les années 1960, en playback comme en musique classique carnatique, et reste l'une des figures les plus respectées de la musique indienne.",
    ],
    keyDates: ["1961 — Débute sa carrière.", "Padma Vibhushan — L'une des plus hautes distinctions civiles indiennes, reçue pour l'ensemble de sa carrière."],
    latest: "Continue de donner des concerts de musique carnatique et de dévotion en Inde et dans la diaspora.",
  },

  // --- Musique classique et instrumentale ---
  {
    slug: "ravi-shankar",
    image: "/artists/ravi-shankar.jpg",
    icon: "note",
    color: "from-violet-700 to-violet-500",
    name: "Ravi Shankar",
    tag: "Maître du sitar",
    region: "classique",
    featured: false,
    short: "Légende du sitar ayant fait connaître la musique classique indienne au monde entier, collaborateur des Beatles.",
    bio: [
      "Ravi Shankar a joué un rôle central dans la diffusion de la musique classique indienne en Occident, notamment via sa collaboration avec George Harrison des Beatles. Il est décédé le 11 décembre 2012.",
    ],
    keyDates: ["1956 — Débute ses tournées internationales.", "11 décembre 2012 — Décès."],
    latest: "Son héritage est perpétué par sa fille Anoushka Shankar, qui continue de tourner avec son répertoire.",
  },
  {
    slug: "anoushka-shankar",
    image: "/artists/anoushka-shankar.jpg",
    icon: "note",
    color: "from-fuchsia-600 to-fuchsia-400",
    name: "Anoushka Shankar",
    tag: "Sitariste",
    region: "classique",
    featured: false,
    short: "Fille de Ravi Shankar, elle perpétue et modernise la tradition du sitar sur les scènes internationales.",
    bio: [
      "Anoushka Shankar a développé une carrière internationale acclamée, mêlant musique classique indienne, musique de chambre occidentale et sonorités électroniques, avec de nombreuses nominations aux Grammy Awards.",
    ],
    keyDates: ["1998 — Sort son premier album.", "2000s-2020s — Multiplie les nominations aux Grammy Awards."],
    latest: "En tournée régulière à travers l'Europe et l'Amérique du Nord ; consultez les plateformes de billetterie pour ses dates 2026.",
  },
  {
    slug: "hariprasad-chaurasia",
    image: "/artists/hariprasad-chaurasia.jpg",
    icon: "note",
    color: "from-sky-600 to-sky-400",
    name: "Hariprasad Chaurasia",
    tag: "Maître de la flûte bansuri",
    region: "classique",
    featured: false,
    short: "L'un des plus grands maîtres de la flûte bansuri, figure centrale de la musique classique hindoustanie.",
    bio: [
      "Hariprasad Chaurasia a fait de la flûte bansuri un instrument de premier plan dans la musique classique hindoustanie, avec une carrière de concertiste internationale depuis plus de cinq décennies.",
    ],
    keyDates: ["Années 1950-60 — Débute sa formation et sa carrière.", "Padma Vibhushan — Reçue pour l'ensemble de sa carrière."],
    latest: "Continue de donner des concerts de musique classique en Inde et à l'international.",
  },
  {
    slug: "amjad-ali-khan",
    image: "/artists/amjad-ali-khan.jpg",
    icon: "note",
    color: "from-stone-700 to-stone-500",
    name: "Ustad Amjad Ali Khan",
    tag: "Maître du sarod",
    region: "classique",
    featured: false,
    short: "L'un des plus grands joueurs de sarod au monde, ambassadeur majeur de la musique classique hindoustanie.",
    bio: [
      "Ustad Amjad Ali Khan est issu d'une lignée de musiciens de sarod remontant à plusieurs générations et s'est imposé comme l'un des concertistes classiques indiens les plus respectés à l'international.",
    ],
    keyDates: ["Années 1960 — Débute sa carrière de concertiste.", "Padma Vibhushan — Reçue pour l'ensemble de sa carrière."],
    latest: "Continue de se produire en concert en Inde et à l'international, souvent accompagné de ses fils, également musiciens.",
  },
];
